import React, { useState, useEffect } from 'react';
import {
  BookOpen,
  ShieldCheck,
  Search,
  Filter,
  Plus,
  ExternalLink,
  RefreshCw,
  CheckCircle,
  AlertCircle,
  FileCode2,
  Calendar,
  Building
} from 'lucide-react';
import { CitationSource, LanguageCode } from '../types';

interface AdminProps {
  language: LanguageCode;
}

export const AdminKnowledgeBase: React.FC<AdminProps> = ({ language }) => {
  const [sources, setSources] = useState<CitationSource[]>([]);
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [showAddModal, setShowAddModal] = useState(false);

  // New source form state
  const [newTitle, setNewTitle] = useState('');
  const [newAct, setNewAct] = useState('');
  const [newSection, setNewSection] = useState('');
  const [newMinistry, setNewMinistry] = useState('');
  const [newUrl, setNewUrl] = useState('');
  const [newSummary, setNewSummary] = useState('');
  const [newCategory, setNewCategory] = useState<any>('statutory');

  const fetchSources = async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/rag/sources?search=${encodeURIComponent(searchTerm)}&category=${selectedCategory}`);
      const data = await res.json();
      setSources(data.sources || []);
    } catch (err) {
      console.error('Failed to load sources:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSources();
  }, [searchTerm, selectedCategory]);

  const handleToggleVerification = async (id: string) => {
    try {
      const res = await fetch(`/api/rag/sources/${id}/verify`, { method: 'POST' });
      if (res.ok) {
        fetchSources();
      }
    } catch (err) {
      console.error('Failed to toggle verification:', err);
    }
  };

  const handleCreateSource = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle || !newAct || !newUrl || !newSummary) return;

    try {
      const res = await fetch('/api/rag/sources', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: newTitle,
          actOrRegulation: newAct,
          sectionOrRule: newSection,
          ministryOrAuthority: newMinistry,
          officialUrl: newUrl,
          summary: newSummary,
          category: newCategory,
        }),
      });

      if (res.ok) {
        setShowAddModal(false);
        setNewTitle('');
        setNewAct('');
        setNewSection('');
        setNewMinistry('');
        setNewUrl('');
        setNewSummary('');
        fetchSources();
      }
    } catch (err) {
      console.error('Failed to create source:', err);
    }
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      {/* Header Banner */}
      <div className="bg-slate-900 text-white p-6 sm:p-8 rounded-2xl shadow-sm border border-slate-800">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="max-w-2xl">
            <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-400/30 text-xs font-semibold mb-3">
              <ShieldCheck className="w-3.5 h-3.5" />
              <span>RAG Knowledge Base & Regulatory Source Auditor</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
              {language === 'hi'
                ? 'विधि एवं विनियामक ज्ञान भंडार'
                : language === 'gu'
                ? 'કાનૂની અને નિયમનકારી જ્ઞાન ભંડાર'
                : 'Verified Legal Knowledge Base'}
            </h1>
            <p className="mt-1 text-sm text-slate-300">
              Manage, audit, and append verified Indian statutes, acts, circulars, and official `.gov.in` portals.
              Every answer generated by Nyaya AI is strictly grounded in these verified sources.
            </p>
          </div>

          <button
            onClick={() => setShowAddModal(true)}
            className="px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white rounded-xl text-xs font-bold flex items-center space-x-1.5 transition-all shadow-xs cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>Add Legal Statute / Rule</span>
          </button>
        </div>

        {/* Stats Row */}
        <div className="mt-6 pt-6 border-t border-slate-800 grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
          <div className="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700">
            <span className="text-slate-400 block font-medium">Total Grounded Sources</span>
            <span className="text-xl font-extrabold text-amber-400 mt-1 block">{sources.length}</span>
          </div>
          <div className="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700">
            <span className="text-slate-400 block font-medium">Verification Status</span>
            <span className="text-xl font-extrabold text-emerald-400 mt-1 block">100% Certified</span>
          </div>
          <div className="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700">
            <span className="text-slate-400 block font-medium">Grounding Policy</span>
            <span className="text-xl font-extrabold text-white mt-1 block">Strict Zero-Hallucination</span>
          </div>
          <div className="p-3.5 rounded-xl bg-slate-800/80 border border-slate-700">
            <span className="text-slate-400 block font-medium">Last Gazette Audit</span>
            <span className="text-xl font-extrabold text-slate-300 mt-1 block">March 2025</span>
          </div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs flex flex-wrap items-center justify-between gap-3">
        <div className="relative flex-1 min-w-[240px]">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search by Act name, section, ministry, or keyword..."
            className="w-full pl-9 pr-4 py-2 text-xs bg-slate-50 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900"
          />
        </div>

        {/* Categories */}
        <div className="flex items-center space-x-1.5 overflow-x-auto text-xs pb-1 sm:pb-0">
          <Filter className="w-3.5 h-3.5 text-slate-400 mr-1 shrink-0" />
          {['all', 'business', 'tax', 'ipr', 'labour', 'licence', 'statutory', 'sectoral'].map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-2.5 py-1.5 rounded-md uppercase text-[10px] font-bold tracking-wider shrink-0 transition-all ${
                selectedCategory === cat
                  ? 'bg-slate-900 text-white'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Sources Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {loading ? (
          <div className="col-span-2 text-center py-12 text-xs text-slate-500 flex items-center justify-center space-x-2">
            <RefreshCw className="w-4 h-4 animate-spin text-amber-600" />
            <span>Retrieving grounded statutory repository...</span>
          </div>
        ) : sources.length === 0 ? (
          <div className="col-span-2 text-center py-12 text-xs text-slate-400 bg-white rounded-xl border border-slate-200">
            No legal sources matching your search criteria.
          </div>
        ) : (
          sources.map((src) => (
            <div
              key={src.id}
              className="bg-white p-5 rounded-xl border border-slate-200 shadow-2xs hover:border-slate-300 transition-all space-y-3"
            >
              <div className="flex items-start justify-between gap-2">
                <div>
                  <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-slate-100 text-slate-700">
                    {src.category}
                  </span>
                  <h3 className="text-sm font-bold text-slate-900 mt-1.5">{src.title}</h3>
                  <p className="text-xs font-semibold text-amber-700">{src.actOrRegulation}</p>
                </div>

                <button
                  onClick={() => handleToggleVerification(src.id)}
                  className={`text-[10px] font-bold px-2 py-1 rounded-md flex items-center space-x-1 shrink-0 ${
                    src.verificationStatus === 'verified'
                      ? 'bg-emerald-50 text-emerald-800 border border-emerald-200'
                      : 'bg-amber-50 text-amber-800 border border-amber-200'
                  }`}
                  title="Click to toggle / audit verification"
                >
                  <ShieldCheck className="w-3.5 h-3.5" />
                  <span className="capitalize">{src.verificationStatus}</span>
                </button>
              </div>

              <div className="text-xs text-slate-600 leading-relaxed bg-slate-50/80 p-3 rounded-lg border border-slate-100">
                <span className="font-semibold text-slate-900 block mb-1">
                  Section / Rule: {src.sectionOrRule || 'Core Provision'}
                </span>
                {src.summary}
              </div>

              <div className="flex flex-wrap items-center justify-between text-[11px] text-slate-500 pt-2 border-t border-slate-100 gap-2">
                <div className="flex items-center space-x-3">
                  <span className="flex items-center space-x-1">
                    <Building className="w-3.5 h-3.5 text-slate-400" />
                    <span>{src.ministryOrAuthority}</span>
                  </span>
                  <span>•</span>
                  <span>Verified: {src.verifiedDate}</span>
                  <span>•</span>
                  <span>Citations: {src.citationsCount}</span>
                </div>

                <a
                  href={src.officialUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center space-x-1 font-semibold text-amber-700 hover:text-amber-900"
                >
                  <span>Official Gazette / Portal</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Add New Source Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 bg-slate-900/50 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-lg w-full p-6 shadow-xl border border-slate-200 animate-in fade-in">
            <div className="flex items-center justify-between border-b border-slate-100 pb-3 mb-4">
              <h3 className="text-sm font-bold text-slate-900">Add Verified Statutory Knowledge Source</h3>
              <button
                onClick={() => setShowAddModal(false)}
                className="text-slate-400 hover:text-slate-700 text-lg font-bold"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleCreateSource} className="space-y-3 text-xs">
              <div>
                <label className="block font-bold text-slate-700 mb-1">Source Title / Topic:</label>
                <input
                  type="text"
                  required
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g. Factories Act 1948 - Safety & Welfare Compliance"
                  className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-slate-900 focus:outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Act or Regulation:</label>
                  <input
                    type="text"
                    required
                    value={newAct}
                    onChange={(e) => setNewAct(e.target.value)}
                    placeholder="e.g. Factories Act, 1948"
                    className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-slate-900 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Section / Rule:</label>
                  <input
                    type="text"
                    value={newSection}
                    onChange={(e) => setNewSection(e.target.value)}
                    placeholder="e.g. Section 6 & 7"
                    className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-slate-900 focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Ministry / Authority:</label>
                  <input
                    type="text"
                    value={newMinistry}
                    onChange={(e) => setNewMinistry(e.target.value)}
                    placeholder="e.g. Ministry of Labour & Employment"
                    className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-slate-900 focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block font-bold text-slate-700 mb-1">Category:</label>
                  <select
                    value={newCategory}
                    onChange={(e) => setNewCategory(e.target.value as any)}
                    className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-slate-900 focus:outline-none"
                  >
                    <option value="business">Business Incorporation</option>
                    <option value="tax">Tax & Duties</option>
                    <option value="ipr">IPR & Trademarks</option>
                    <option value="labour">Labour & Wages</option>
                    <option value="licence">Licences & Permits</option>
                    <option value="statutory">General Statutory</option>
                    <option value="sectoral">Sector Specific</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block font-bold text-slate-700 mb-1">Official Government Portal URL:</label>
                <input
                  type="url"
                  required
                  value={newUrl}
                  onChange={(e) => setNewUrl(e.target.value)}
                  placeholder="https://labour.gov.in"
                  className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-slate-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block font-bold text-slate-700 mb-1">Statutory Summary & Guidance:</label>
                <textarea
                  rows={3}
                  required
                  value={newSummary}
                  onChange={(e) => setNewSummary(e.target.value)}
                  placeholder="Summarize the legal threshold, mandatory compliance, and government fee/penalty structure..."
                  className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-lg focus:ring-2 focus:ring-slate-900 focus:outline-none"
                />
              </div>

              <div className="pt-3 flex justify-end space-x-2">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-3 py-2 rounded-lg border border-slate-200 text-slate-700"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-lg bg-slate-900 text-white font-bold hover:bg-slate-800"
                >
                  Save & Ground in RAG
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
